
name: F-AI Accountant CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r package_requirements.txt
    
    - name: Set up database
      run: |
        python database/database_manager.py setup
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Check application startup
      run: |
        timeout 30 python main.py &
        sleep 10
        curl -f http://localhost:5000/health || exit 1
